CTFd/admin/__init__.py
import csv
import datetime
import os

import six
from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

from CTFd.cache import cache, clear_config
from CTFd.models import (
    Awards,
    Configs,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
    get_class_by_tablename,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_config, set_config
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.exports import import_ctf as import_ctf_util
from CTFd.utils.helpers import get_errors
from CTFd.utils.security.auth import logout_user
from CTFd.utils.user import is_admin

admin = Blueprint("admin", __name__)

from CTFd.admin import challenges  # noqa: F401
from CTFd.admin import notifications  # noqa: F401
from CTFd.admin import pages  # noqa: F401
from CTFd.admin import scoreboard  # noqa: F401
from CTFd.admin import statistics  # noqa: F401
from CTFd.admin import submissions  # noqa: F401
from CTFd.admin import teams  # noqa: F401
from CTFd.admin import users  # noqa: F401


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["POST"])
@admins_only
def import_ctf():
    backup = request.files["backup"]
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for("admin.config"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    # TODO: It might make sense to limit dumpable tables. Config could potentially leak sensitive information.
    model = get_class_by_tablename(table)
    if model is None:
        abort(404)

    temp = six.StringIO()
    writer = csv.writer(temp)

    header = [column.name for column in model.__mapper__.columns]
    writer.writerow(header)

    responses = model.query.all()

    for curr in responses:
        writer.writerow(
            [getattr(curr, column.name) for column in model.__mapper__.columns]
        )

    temp.seek(0)

    # In Python 3 send_file requires bytes
    output = six.BytesIO()
    output.write(temp.getvalue().encode("utf-8"))
    output.seek(0)
    temp.close()

    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    database_tables = sorted(db.metadata.tables.keys())

    configs = Configs.query.all()
    configs = dict([(c.key, get_config(c.key)) for c in configs])

    themes = ctf_config.get_themes()
    themes.remove(get_config("ctf_theme"))

    return render_template(
        "admin/config.html", database_tables=database_tables, themes=themes, **configs
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        # Truncate Users, Teams, Submissions, Solves, Notifications, Awards, Unlocks, Tracking
        Tracking.query.delete()
        Solves.query.delete()
        Submissions.query.delete()
        Awards.query.delete()
        Unlocks.query.delete()
        Users.query.delete()
        Teams.query.delete()
        set_config("setup", False)
        db.session.commit()
        cache.clear()
        logout_user()
        db.session.close()
        return redirect(url_for("views.setup"))

    return render_template("admin/reset.html")

CTFd/auth.py
import base64

import requests
from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, session, url_for
from itsdangerous.exc import BadSignature, BadTimeSignature, SignatureExpired

from CTFd.models import Teams, Users, db
from CTFd.utils import config, email, get_app_config, get_config
from CTFd.utils import user as current_user
from CTFd.utils import validators
from CTFd.utils.config import is_teams_mode
from CTFd.utils.config.integrations import mlc_registration
from CTFd.utils.config.visibility import registration_visible
from CTFd.utils.crypto import verify_password
from CTFd.utils.decorators import ratelimit
from CTFd.utils.decorators.visibility import check_registration_visibility
from CTFd.utils.helpers import error_for, get_errors
from CTFd.utils.logging import log
from CTFd.utils.modes import TEAMS_MODE
from CTFd.utils.security.auth import login_user, logout_user
from CTFd.utils.security.signing import unserialize

auth = Blueprint("auth", __name__)


@auth.route("/confirm", methods=["POST", "GET"])
@auth.route("/confirm/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def confirm(data=None):
    if not get_config("verify_emails"):
        # If the CTF doesn't care about confirming email addresses then redierct to challenges
        return redirect(url_for("challenges.listing"))

    # User is confirming email account
    if data and request.method == "GET":
        try:
            user_email = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template(
                "confirm.html", errors=["Your confirmation link has expired"]
            )
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template(
                "confirm.html", errors=["Your confirmation token is invalid"]
            )

        user = Users.query.filter_by(email=user_email).first_or_404()
        if user.verified:
            return redirect(url_for("views.settings"))

        user.verified = True
        log(
            "registrations",
            format="[{date}] {ip} - successful confirmation for {name}",
            name=user.name,
        )
        db.session.commit()
        email.successful_registration_notification(user.email)
        db.session.close()
        if current_user.authed():
            return redirect(url_for("challenges.listing"))
        return redirect(url_for("auth.login"))

    # User is trying to start or restart the confirmation flow
    if not current_user.authed():
        return redirect(url_for("auth.login"))

    user = Users.query.filter_by(id=session["id"]).first_or_404()
    if user.verified:
        return redirect(url_for("views.settings"))

    if data is None:
        if request.method == "POST":
            # User wants to resend their confirmation email
            email.verify_email_address(user.email)
            log(
                "registrations",
                format="[{date}] {ip} - {name} initiated a confirmation email resend",
            )
            return render_template(
                "confirm.html",
                user=user,
                infos=["Your confirmation email has been resent!"],
            )
        elif request.method == "GET":
            # User has been directed to the confirm page
            return render_template("confirm.html", user=user)


@auth.route("/reset_password", methods=["POST", "GET"])
@auth.route("/reset_password/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def reset_password(data=None):
    if data is not None:
        try:
            email_address = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template(
                "reset_password.html", errors=["Your link has expired"]
            )
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template(
                "reset_password.html", errors=["Your reset token is invalid"]
            )

        if request.method == "GET":
            return render_template("reset_password.html", mode="set")
        if request.method == "POST":
            password = request.form.get("password", "").strip()
            user = Users.query.filter_by(email=email_address).first_or_404()
            if user.oauth_id:
                return render_template(
                    "reset_password.html",
                    errors=[
                        "Your account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                    ],
                )

            pass_short = len(password) == 0
            if pass_short:
                return render_template(
                    "reset_password.html", errors=["Please pick a longer password"]
                )

            user.password = password
            db.session.commit()
            log(
                "logins",
                format="[{date}] {ip} -  successful password reset for {name}",
                name=user.name,
            )
            db.session.close()
            email.password_change_alert(user.email)
            return redirect(url_for("auth.login"))

    if request.method == "POST":
        email_address = request.form["email"].strip()
        user = Users.query.filter_by(email=email_address).first()

        get_errors()

        if config.can_send_mail() is False:
            return render_template(
                "reset_password.html",
                errors=["Email could not be sent due to server misconfiguration"],
            )

        if not user:
            return render_template(
                "reset_password.html",
                errors=[
                    "If that account exists you will receive an email, please check your inbox"
                ],
            )

        if user.oauth_id:
            return render_template(
                "reset_password.html",
                errors=[
                    "The email address associated with this account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                ],
            )

        email.forgot_password(email_address)

        return render_template(
            "reset_password.html",
            errors=[
                "If that account exists you will receive an email, please check your inbox"
            ],
        )
    return render_template("reset_password.html")


@auth.route("/register", methods=["POST", "GET"])
@check_registration_visibility
@ratelimit(method="POST", limit=10, interval=5)
def register():
    errors = get_errors()
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email_address = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "").strip()

        name_len = len(name) == 0
        names = Users.query.add_columns("name", "id").filter_by(name=name).first()
        emails = (
            Users.query.add_columns("email", "id")
            .filter_by(email=email_address)
            .first()
        )
        pass_short = len(password) == 0
        pass_long = len(password) > 128
        valid_email = validators.validate_email(email_address)
        team_name_email_check = validators.validate_email(name)

        if not valid_email:
            errors.append("Please enter a valid email address")
        if email.check_email_is_whitelisted(email_address) is False:
            errors.append(
                "Only email addresses under {domains} may register".format(
                    domains=get_config("domain_whitelist")
                )
            )
        if names:
            errors.append("That user name is already taken")
        if team_name_email_check is True:
            errors.append("Your user name cannot be an email address")
        if emails:
            errors.append("That email has already been used")
        if pass_short:
            errors.append("Pick a longer password")
        if pass_long:
            errors.append("Pick a shorter password")
        if name_len:
            errors.append("Pick a longer user name")

        if len(errors) > 0:
            return render_template(
                "register.html",
                errors=errors,
                name=request.form["name"],
                email=request.form["email"],
                password=request.form["password"],
            )
        else:
            with app.app_context():
                user = Users(name=name, email=email_address, password=password)
                db.session.add(user)
                db.session.commit()
                db.session.flush()

                login_user(user)

                if config.can_send_mail() and get_config(
                    "verify_emails"
                ):  # Confirming users is enabled and we can send email.
                    log(
                        "registrations",
                        format="[{date}] {ip} - {name} registered (UNCONFIRMED) with {email}",
                    )
                    email.verify_email_address(user.email)
                    db.session.close()
                    return redirect(url_for("auth.confirm"))
                else:  # Don't care about confirming users
                    if (
                        config.can_send_mail()
                    ):  # We want to notify the user that they have registered.
                        email.successful_registration_notification(user.email)

        log("registrations", "[{date}] {ip} - {name} registered with {email}")
        db.session.close()

        if is_teams_mode():
            return redirect(url_for("teams.private"))

        return redirect(url_for("challenges.listing"))
    else:

CTFd/themes/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ get_ctf_name() }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{{ url_for('views.themes', path='img/favicon.ico') }}" type="image/x-icon">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/fonts.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/core.css') }}">
	{% block stylesheets %}{% endblock %}
	{% for stylesheet in get_registered_stylesheets() %}
		{% if stylesheet.startswith('http') %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% elif request.script_root %}
			<link rel="stylesheet" type="text/css" href="{{ request.script_root }}/{{ stylesheet }}">
		{% else %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% endif %}
	{% endfor %}
	<script type="text/javascript">
		var init = {
			'urlRoot': "{{ request.script_root }}",
			'csrfNonce': "{{ nonce }}",
			'userMode': "{{ get_config('user_mode') }}",
			'userId': {{ id if (id is defined) else 0 }},
			'start': {{ get_config("start") | tojson }},
			'end': {{ get_config("end") | tojson }},
		}
	</script>
	{{ get_config('theme_header', '') | safe }}
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<div class="container">
			<a href="{{ url_for('views.static_html', route='/') }}" class="navbar-brand">
				{% if get_ctf_logo() %}
				<img class="img-responsive ctf_logo" src="{{ url_for('views.files', path=get_ctf_logo()) }}" height="25" alt="{{ get_ctf_name() }}">
				{% else %}
				{{ get_ctf_name() }}
				{% endif %}
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#base-navbars"
					aria-controls="base-navbars" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="base-navbars">
				<ul class="navbar-nav mr-auto">
					{% for page in get_user_page_menu_bar() %}
						{% if page.route.startswith('http://') or page.route.startswith('https://') %}
							<li class="nav-item">
								<a class="nav-link" href="{{ page.route }}">{{ page.title }}</a>
							</li>
						{% else %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('views.static_html', route=page.route) }}">{{ page.title }}</a>
							</li>
						{% endif %}
					{% endfor %}

					{% if get_config('account_visibility') != 'admins' %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.listing') }}">Users</a>
						</li>
						{% if get_config('user_mode') == 'teams' %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('teams.listing') }}">Teams</a>
						</li>
						{% endif %}
					{% endif %}
					{% if get_config('score_visibility') != 'admins' %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('scoreboard.listing') }}">Scoreboard</a>
						</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('challenges.listing') }}">Challenges</a>
					</li>
				</ul>

				<hr class="d-sm-flex d-md-flex d-lg-none">

				<ul class="navbar-nav ml-md-auto d-block d-sm-flex d-md-flex">
					{% if authed() %}
						{% if type == 'admin' %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('admin.view') }}">
									<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Admin Panel">
										<i class="fas fa-wrench d-none d-md-block d-lg-none"></i>
									</span>
									<span class="d-sm-block d-md-none d-lg-block">
										<i class="fas fa-wrench pr-1"></i>Admin Panel
									</span>
								</a>
							</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('views.notifications') }}">
								<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Notifications">
									<i class="fas fa-bell d-none d-md-block d-lg-none"></i>
								</span>
								<span class="d-sm-block d-md-none d-lg-block">
									<i class="fas fa-bell pr-1"></i>
									<span class="badge badge-pill badge-danger badge-notification"></span>
									Notifications
								</span>
							</a>
						</li>
						{% if config.user_mode() == "teams" %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('teams.private') }}">
								<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Team">
									<i class="fas fa-users d-none d-md-block d-lg-none"></i>
								</span>
								<span class="d-sm-block d-md-none d-lg-block">
									<i class="fas fa-users pr-1"></i>Team
								</span>
							</a>
						</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.private') }}">
								<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Profile">
									<i class="fas fa-user-circle d-none d-md-block d-lg-none"></i>
								</span>
								<span class="d-sm-block d-md-none d-lg-block">
									<i class="fas fa-user-circle pr-1"></i>Profile
								</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('views.settings') }}">
								<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Settings">
									<i class="fas fa-cogs d-none d-md-block d-lg-none"></i>
								</span>
								<span class="d-sm-block d-md-none d-lg-block">
									<i class="fas fa-cogs pr-1"></i>Settings
								</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('auth.logout') }}">
								<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Logout">
									<i class="fas fa-sign-out-alt d-none d-md-block d-lg-none"></i>
								</span>
								<span class="d-sm-block d-md-none d-lg-block">
									<i class="fas fa-sign-out-alt pr-1"></i><span class="d-lg-none">Logout</span>
								</span>
							</a>
						</li>
					{% else %}
						{% if registration_visible() %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('auth.register') }}">
									<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Register">
										<i class="fas fa-user-plus d-none d-md-block d-lg-none"></i>
									</span>
									<span class="d-sm-block d-md-none d-lg-block">
										<i class="fas fa-user-plus pr-1"></i>Register
									</span>
								</a>
							</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('auth.login') }}">
								<span class="d-block" data-toggle="tooltip" data-placement="bottom" title="Login">
									<i class="fas fa-sign-in-alt d-none d-md-block d-lg-none"></i>
								</span>
								<span class="d-sm-block d-md-none d-lg-block">
									<i class="fas fa-sign-in-alt pr-1"></i>Login
								</span>
							</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<main role="main">
		{% block content %}
		{% endblock %}
	</main>

	<footer class="footer">
		<div class="container text-center">
			<a href="https://ctfd.io" class="text-secondary">
				<small class="text-muted">Powered by CTFd</small>
			</a>
		</div>
	</footer>

	<script defer src="{{ url_for('views.themes', path='js/vendor.bundle.js') }}"></script>
	<script defer src="{{ url_for('views.themes', path='js/core.js') }}"></script>
	<script defer src="{{ url_for('views.themes', path='js/helpers.js') }}"></script>

	{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', path='js/pages/main.js') }}"></script>
	{% endblock %}

	{% block scripts %}
	{% endblock %}

	{% for script in get_registered_scripts() %}
	{% if script.startswith('http') %}
	<script defer src="{{ script }}"></script>
	{% elif request.script_root %}
	<script defer src="{{ request.script_root }}/{{ script }}"></script>
	{% else %}
	<script defer src="{{ script }}"></script>
	{% endif %}
	{% endfor %}

	{{ get_config('theme_footer', '') | safe }}
</body>
</html>

CTFd/themes/core/templates/challenges.html
{% extends "base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/challenge-board.css') }}">
{% endblock %}

{% block content %}

<div class="jumbotron">
	<div class="container">
		<h1>Challenges</h1>
	</div>
</div>

{% if infos %}
	<div class="container">
		<div id='errors' class="row">
			<div class="col-md-12">
				{% for info in infos %}
					<h1 class="text-center">{{ info }}</h1>
				{% endfor %}
			</div>
		</div>
	</div>
{% endif %}

{% if errors %}
<div class="container">
	<div id='errors' class="row">
		<div class="col-md-12">
{% for error in errors %}
			<h1 class="text-center">{{ error }}</h1>
{% endfor %}
		</div>
	</div>
</div>
{% endif %}

{% if admin or not errors %}
<div class="container">
	<div id='challenges-board'>
		<div class="text-center">
			<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
		</div>
	</div>
</div>

<input id="nonce" type="hidden" name="nonce" value="{{ nonce }}">

<div class="modal fade" id="challenge-window" tabindex="-1" role="dialog">
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	{% if admin or not errors %}
		<script defer src="{{ url_for('views.themes', path='js/pages/challenges.js') }}"></script>
	{% endif %}
{% endblock %}

CTFd/themes/core/templates/confirm.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Confirm</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				{% for info in infos %}
					<div class="alert alert-info alert-dismissable" role="alert">
						<span class="sr-only"></span>
						{{ info }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
								aria-hidden="true">×</span></button>
					</div>
				{% endfor %}
				{% for error in errors %}
					<div class="alert alert-danger alert-dismissable" role="alert">
						<span class="sr-only">Error:</span>
						{{ error }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
								aria-hidden="true">×</span></button>
					</div>
				{% endfor %}
				{% if user %}
				<h3 class="text-center">
					We've sent a confirmation email to {{ user.email }}
				</h3>

				<br>

				<h4 class="text-center">
					Please click the link in that email to confirm your account.
				</h4>
				{% endif %}

				<hr>

				{% if name %}
				<form method="POST" action="{{ url_for('auth.confirm') }}">
					<h4 class="text-center">
						Need to resend the confirmation email?
					</h4>
					<div class="col-md-12 text-center">
						<button type="submit" tabindex="0" class="btn btn-md btn-primary btn-outlined">Resend</button>
					</div>
					<input type="hidden" name="nonce" value="{{ nonce }}">
				</form>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
{% endblock %}

CTFd/themes/core/templates/login.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Login</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% for error in errors %}
				<div class="alert alert-danger alert-dismissable" role="alert">
				  <span class="sr-only">Error:</span>
				  {{ error }}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				</div>
			{% endfor %}

			{% if integrations.mlc() %}
			<a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('auth.oauth_login') }}">
				Login with Major League Cyber
			</a>

			<hr>
			{% endif %}

			<form method="post" accept-charset="utf-8" autocomplete="off" role="form" class="form-horizontal">
				<div class="form-group">
					<label for="name-input">
						User Name or Email
					</label>
					<input class="form-control" type="text" name="name" id="name-input" />
				</div>
				<div class="form-group">
					<label for="password-input">
						Password
					</label>
					<input class="form-control" type="password" name="password" id="password-input" />
				</div>
				<div class="row pt-3">
					<div class="col-md-6">
						<a class="float-left align-text-to-button" href="{{ url_for('auth.reset_password') }}">
							Forgot your password?
						</a>
					</div>
					<div class="col-md-6">
						<button type="submit" tabindex="0" class="btn btn-md btn-primary btn-outlined float-right">
							Submit
						</button>
					</div>
				</div>
				<input type="hidden" name="nonce" value="{{ nonce }}">
			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

CTFd/themes/core/templates/notifications.html
{% extends "base.html" %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Notifications</h1>
		</div>
	</div>
	<div class="container">
		{% if not notifications %}
		<h2 class="text-center">There are no notifications yet</h2>
		{% endif %}
		{% for notification in notifications %}
		<div class="card bg-light mb-4">
			<div class="card-body">
				<h3 class="card-title">{{ notification.title }}</h3>
				<blockquote class="blockquote mb-0">
					<p>{{ notification.content | safe }}</p>
					<small class="text-muted"><span data-time="{{ notification.date | isoformat }}"></span></small>
				</blockquote>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', path='js/pages/notifications.js') }}"></script>
{% endblock %}

CTFd/themes/core/templates/page.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
	{{ content | safe }}
	</div>
{% endblock %}

CTFd/themes/core/templates/register.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Register</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% for error in errors %}
				<div class="alert alert-danger alert-dismissable" role="alert">
				  <span class="sr-only">Error:</span>
				  {{ error }}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				</div>
			{% endfor %}

			{% if integrations.mlc() %}
			<a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('auth.oauth_login') }}">
				Login with Major League Cyber
			</a>

			<hr>
			{% endif %}

			<form method="post" accept-charset="utf-8" autocomplete="off" role="form" class="form-horizontal">
				<div class="form-group">
					<label for="name-input">
						User Name
					</label>
					<input class="form-control" type="text" name="name" id="name-input" {% if name %}value="{{ name }}"{% endif %} />
				</div>
				<div class="form-group">
					<label for="email-input">
						Email
					</label>
					<input class="form-control" type="text" name="email" id="email-input" {% if email %}value="{{ email }}"{% endif %} />
				</div>
				<div class="form-group">
					<label for="password-input">
						Password
					</label>
					<input class="form-control" type="password" name="password" id="password-input" {% if password %}value="{{ password }}"{% endif %}/>
				</div>
				<div class="row pt-3">
					<div class="col-md-12">
						<button type="submit" tabindex="0" class="btn btn-md btn-primary btn-outlined float-right">Submit</button>
					</div>
				</div>
				<input type="hidden" name="nonce" value="{{ nonce }}">
			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}