CTFd/admin/__init__.py
import csv
import datetime
import os

import six
from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

from CTFd.cache import cache, clear_config
from CTFd.models import (
    Awards,
    Configs,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
    get_class_by_tablename,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_config, set_config
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.exports import import_ctf as import_ctf_util
from CTFd.utils.helpers import get_errors
from CTFd.utils.security.auth import logout_user
from CTFd.utils.user import is_admin

admin = Blueprint("admin", __name__)

from CTFd.admin import challenges  # noqa: F401
from CTFd.admin import notifications  # noqa: F401
from CTFd.admin import pages  # noqa: F401
from CTFd.admin import scoreboard  # noqa: F401
from CTFd.admin import statistics  # noqa: F401
from CTFd.admin import submissions  # noqa: F401
from CTFd.admin import teams  # noqa: F401
from CTFd.admin import users  # noqa: F401


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["POST"])
@admins_only
def import_ctf():
    backup = request.files["backup"]
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for("admin.config"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    # TODO: It might make sense to limit dumpable tables. Config could potentially leak sensitive information.
    model = get_class_by_tablename(table)
    if model is None:
        abort(404)

    temp = six.StringIO()
    writer = csv.writer(temp)

    header = [column.name for column in model.__mapper__.columns]
    writer.writerow(header)

    responses = model.query.all()

    for curr in responses:
        writer.writerow(
            [getattr(curr, column.name) for column in model.__mapper__.columns]
        )

    temp.seek(0)

    # In Python 3 send_file requires bytes
    output = six.BytesIO()
    output.write(temp.getvalue().encode("utf-8"))
    output.seek(0)
    temp.close()

    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    database_tables = sorted(db.metadata.tables.keys())

    configs = Configs.query.all()
    configs = dict([(c.key, get_config(c.key)) for c in configs])

    themes = ctf_config.get_themes()
    themes.remove(get_config("ctf_theme"))

    return render_template(
        "admin/config.html", database_tables=database_tables, themes=themes, **configs
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        # Truncate Users, Teams, Submissions, Solves, Notifications, Awards, Unlocks, Tracking
        Tracking.query.delete()
        Solves.query.delete()
        Submissions.query.delete()
        Awards.query.delete()
        Unlocks.query.delete()
        Users.query.delete()
        Teams.query.delete()
        set_config("setup", False)
        db.session.commit()
        cache.clear()
        logout_user()
        db.session.close()
        return redirect(url_for("views.setup"))

    return render_template("admin/reset.html")

CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.utils import get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

CTFd/themes/admin/templates/configs/accounts.html
<div role="tabpanel" class="tab-pane config-section" id="accounts">
	<form method="POST" autocomplete="off" class="w-100">

		<div class="form-group">
			<label>
				Account Email Whitelist
				<small class="form-text text-muted">
					Comma-seperated email domains which users can register under.
				</small>
			</label>
			<input class="form-control" id='domain-whitelist' name='domain_whitelist' type='text'
				   placeholder=""
				   {% if domain_whitelist is defined and domain_whitelist != None %}value="{{ domain_whitelist }}"{% endif %}>
			<small class="form-text text-muted">
				e.g. ctfd.io,gmail.com,yahoo.com
			</small>
		</div>

		<div class="form-group">
			<label>
				Verify Emails<br>
				<small class="form-text text-muted">
					Control whether users must confirm their email addresses before playing
				</small>
			</label>
			<select class="form-control custom-select" name="verify_emails">
				<option value="true" {% if verify_emails == True %}selected{% endif %}>Enabled</option>
				<option value="false" {% if verify_emails == False or verify_emails == None %}selected{% endif %}>Disabled</option>
			</select>
		</div>

		<div class="form-group">
			<label>
				Team Size<br>
				<small class="form-text text-muted">
					Amount of users per team
				</small>
			</label>
			<input class="form-control" id="team_size" name="team_size" type="number" min="0" {% if team_size %}value="{{ team_size }}"{% endif %}>
		</div>

		<div class="form-group">
			<label>
				Name Changes<br>
				<small class="form-text text-muted">
					Control whether users can change their names
				</small>
			</label>
			<select class="form-control custom-select" name="name_changes">
				<option value="true" {% if name_changes == True or name_changes == None %}selected{% endif %}>Enabled</option>
				<option value="false" {% if name_changes == False %}selected{% endif %}>Disabled</option>
			</select>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/appearance.html
<div role="tabpanel" class="tab-pane config-section active" id="appearance">
	<form id="logo-upload" class="form-upload" method="POST" enctype="multipart/form-data">
		<div class="form-group">
			<label for="ctf_logo">
				Logo
				<small class="form-text text-muted">
					Logo to use for the website instead of a CTF name.
				</small>
			</label>

			{% if ctf_logo %}
				<div class="d-block py-3">
					<img id="ctf_logo_preview" class="img-responsive ctf_logo"
						 src="{{ url_for('views.files', path=ctf_logo) }}"
						 height="25">
					<button type="button" id="remove-logo" class="btn-sm btn-danger">
						Remove Logo
					</button>
				</div>
			{% endif %}

			<div class="row">
				<div class="col-md-9">
					<input class="form-control-file" id="ctf_logo_file" name='file' type='file'
						   placeholder="CTF Logo">
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<div class="d-inline-block float-right">
							<button type="submit" class="btn-sm btn-primary float-right">Upload</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>

	<hr>

	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<label for="ctf_name">
				Competition Name
				<small class="form-text text-muted">Competition name displayed instead of a logo</small>
			</label>
			<input class="form-control" id='ctf_name' name='ctf_name' type='text' placeholder="CTF Name"
				   {% if ctf_name is defined and ctf_name != None %}value="{{ ctf_name }}"{% endif %}>
		</div>

		<div class="form-group">
			<label>
				CTF Description<br>
				<small class="form-text text-muted">
					Description for the CTF
				</small>
			</label>
			<textarea class="form-control" type="text" id="ctf_description" name="ctf_description" rows="5">{{ ctf_description }}</textarea>
		</div>

		<div class="form-group">
			<label for="user_mode">
				User Mode
				<small class="form-text text-muted">User mode allows users to register as themselves
					or choose to form teams.
				</small>
			</label>
			<div data-toggle="tooltip" data-placement="bottom" title="In order to change User Mode you must reset your CTF">
				<select class="form-control custom-select" id="user_mode" name="user_mode" disabled="true" style="z-index: -1;">
					<option value="teams" {% if user_mode == 'teams' %}selected{% endif %}>
						Teams
					</option>
					<option value="users" {% if user_mode == 'users' %}selected{% endif %}>
						Users
					</option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label for="ctf_theme">
				Theme
				<small class="form-text text-muted">
					Switch themes to change CTFd's aesthetics
				</small>
			</label>
			<select class="form-control custom-select" id="ctf_theme" name="ctf_theme">
				<option>{{ ctf_theme }}</option>
				{% for theme in themes %}
					<option>{{ theme }}</option>
				{% endfor %}
			</select>
		</div>

		<div class="form-group">
			<label>
				Theme Color
				<small class="form-text text-muted">
					Color used by theme to control aesthetics. Requires theme support.
				</small>
			</label>
			<div class="d-inline-block">
				<input type="color" id="config-color-picker">
				<button type="button" class="btn-sm btn-primary" id="config-color-update">Update CSS</button>
			</div>
		</div>

		<div class="form-group">
			<label>
				Theme Header
				<small class="form-text text-muted">
					Theme headers are inserted just before the <code>&lt;/head&gt;</code> tag on all public facing pages.
					Requires theme support.
				</small>
			</label>
			<textarea class="form-control" id="theme-header" name="theme_header" rows="7">{{ theme_header or "" }}</textarea>
		</div>

		<div class="form-group">
			<label>
				Theme Footer
				<small class="form-text text-muted">
					Theme footers are inserted just before the <code>&lt;/body&gt;</code> tag on all public facing pages.
					Requires theme support.
				</small>
			</label>
			<textarea class="form-control" id="theme-footer" name="theme_footer" rows="7">{{ theme_footer or "" }}</textarea>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/backup.html
<div role="tabpanel" class="tab-pane config-section" id="backup">
	<ul class="nav nav-tabs mb-3" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" href="#export-ctf" aria-controls="export-ctf" role="tab"
			   data-toggle="tab">Export</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#import-ctf" aria-controls="import-ctf" role="tab" data-toggle="tab">Import</a>
		</li>
		<li class="nav-item">
			<a class="nav-link " href="#save-csv" aria-controls="save-csv" role="tab" data-toggle="tab">Download CSV</a>
		</li>
	</ul>
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="export-ctf">
			<div class="form-group">
				<p>Exports are an archive of your CTF in its current state. They can be re-imported into other CTFd
					instances or used by scripts and third parties to calculate statistics.</p>
				<p>To download an export click the button below.</p>
			</div>
			<div class="form-group">
				<a href="{{ url_for('admin.export_ctf') }}" id="export-button" class="btn btn-warning">Export</a>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="import-ctf">
			<div class="form-group">
				<p>You can import saved CTFd exports by uploading them below. This will completely wipe your existing
					CTFd instance and all your data will be replaced by the imported data.
					You should only import data that you trust!</p>

				<div class="alert alert-warning" role="alert">
					IMPORTING A CTF WILL COMPLETELY WIPE YOUR EXISTING DATA
				</div>
			</div>
			<div class="form-group">
				<label for="container-files">Import File</label>
				<input class="form-control-file" type="file" name="backup" id="import-file" accept=".zip">
			</div>
			<input id="import-button" type="submit" class="btn btn-warning" value="Import">
		</div>
		<div role="tabpanel" class="tab-pane" id="save-csv">
			<form method="GET" action="{{ url_for('admin.export_csv') }}">
				<div class="form-group">
					<label for="container-files">Database Table</label>
					<select class="form-control custom-select" name="table">
						{% for table in database_tables %}
							<option value="{{ table }}">{{ table }}</option>
						{% endfor %}
					</select>
				</div>
				<input type="submit" class="btn btn-warning" value="Download CSV">
			</form>
		</div>
	</div>
</div>

CTFd/themes/admin/templates/configs/email.html
<div role="tabpanel" class="tab-pane config-section" id="email">
	<form method="POST" autocomplete="off" class="w-100">
		<h5>Email Content</h5>
		<small class="form-text text-muted">
			Customize CTFd emails with <a href="https://help.ctfd.io/configuration/emails/#email-content" target="_blank">predefined variables</a> and custom content
		</small>
		<ul class="nav nav-tabs mt-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#confirmation-email-tab" role="tab" data-toggle="tab">
					Confirmation
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#account-details-email-tab" role="tab" data-toggle="tab">Account Details</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#password-reset-email-tab" role="tab" data-toggle="tab">Password Reset</a>
			</li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="confirmation-email-tab">
				<div class="form-group">
					<label class="pt-3">
						Account Registration<br>
						<small class="form-text text-muted">
							Email sent to users after they've registered their account entirely
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='successful_registration_email_subject' name='successful_registration_email_subject' type='text'
							value="{{ successful_registration_email_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="successful_registration_email_body" name="verification_email_body"
							rows="5">{{ successful_registration_email_body or '' }}</textarea>
					</div>
				</div>

				<div class="form-group">
					<label class="pt-3">
						Account Confirmation<br>
						<small class="form-text text-muted">
							Email sent to users to confirm their account
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='verification_email_subject' name='verification_email_subject' type='text' value="{{ verification_email_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="verification_email_body" name="verification_email_body"
							rows="5">{{ verification_email_body or '' }}</textarea>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="account-details-email-tab">
				<div class="form-group">
					<label class="pt-3">
						New Account Details<br>
						<small class="form-text text-muted">
							Email sent to new users (created by an admin) with their initial account details
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='user_creation_email_subject' name='user_creation_email_subject' type='text'
							value="{{ user_creation_email_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="user_creation_email_body" name="user_creation_email_body"
							rows="5">{{ user_creation_email_body or '' }}</textarea>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="password-reset-email-tab">
				<div class="form-group">
					<label class="pt-3">
						Password Reset Request<br>
						<small class="form-text text-muted">
							Email sent whent a user requests a password reset
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='password_reset_subject' name='password_reset_subject' type='text'
							value="{{ password_reset_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="password_reset_body" name="password_reset_body"
							rows="5">{{ password_reset_body or '' }}</textarea>
					</div>
				</div>

				<div class="form-group">
					<label class="pt-3">
						Password Reset Confirmation<br>
						<small class="form-text text-muted">
							Email sent whent a user successfully resets their password
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='password_change_alert_subject' name='password_change_alert_subject' type='text'
							value="{{ password_change_alert_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="password_change_alert_body" name="password_change_alert_body"
							rows="5">{{ password_change_alert_body or '' }}</textarea>
					</div>
				</div>
			</div>
		</div>

		<hr class="my-5">

		<h5>Email Server</h5>
		<small class="form-text text-muted">
			Change the email server used by CTFd to send email
		</small>
		<ul class="nav nav-tabs my-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#mailserver" role="tab" data-toggle="tab">Mail
					Server</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#mailgun" role="tab" data-toggle="tab">Mailgun</a>
			</li>
		</ul>

		<div class="form-group">
			<label>
				Mail From Address<br>
				<small class="form-text text-muted">
					Email address used to send email
				</small>
			</label>
			<input class="form-control" id='mailfrom_addr' name='mailfrom_addr' type='text' {% if mailfrom_addr is defined and mailfrom_addr != None %}value="{{ mailfrom_addr }}"{% endif %}>
		</div>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="mailserver">

				<div class="form-group">
					<label>
						Mail Server Address<br>
						<small class="form-text text-muted">
							Mail Server Address
						</small>
					</label>
					<input class="form-control" id='mail_server' name='mail_server' type='text'
						   {% if mail_server is defined and mail_server != None %}value="{{ mail_server }}"{% endif %}>
				</div>

				<div class="form-group">
					<label>
						Mail Server Port<br>
						<small class="form-text text-muted">
							Mail Server Port
						</small>
					</label>
					<input class="form-control" id='mail_port' name='mail_port' type='text'
						   {% if mail_port is defined and mail_port != None %}value="{{ mail_port }}"{% endif %}>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_useauth" name="mail_useauth" type="checkbox"
							   {% if mail_useauth %}checked{% endif %}>
						Use Mail Server Username and Password
					</label>
				</div>
				<div id="mail_username_password">
					<div class="form-group">
						<label>
							Username<br>
							<small class="form-text text-muted">
								Mail Server Account Username
							</small>
						</label>
						{% if mail_username is defined and mail_username != None %}
							<label>
								<sup class="form-text text-muted">A mail server username is currently set</sup>
							</label>
						{% endif %}
						<input class="form-control" id='mail_username' name='mail_username' autocomplete='off' type='text'>
					</div>
					<div class="form-group">
						<label for="mail_password">
							Password<br>
							<small class="form-text text-muted">
								Mail Server Account Password
							</small>
						</label>
						{% if mail_password is defined and mail_password != None %}
							<label>
								<sup class="form-text text-muted">An mail server password is currently set</sup>
							</label>
						{% endif %}
						<input class="form-control" id='mail_password' name='mail_password' autocomplete='off' type='password'>
					</div>
					<sup>Uncheck setting and update to remove username and password</sup>
					<br>
					<br>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_ssl" name="mail_ssl" type="checkbox" {% if mail_ssl %}checked{% endif %}>
						SSL
					</label>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_tls" name="mail_tls" type="checkbox" {% if mail_tls %}checked{% endif %}>
						TLS
					</label>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="mailgun">
				<div class="form-group">
					<label>
						Mailgun API Base URL<br>
						<small class="form-text text-muted">
							Mailgun API Base URL
						</small>
					</label>
					<input class="form-control" id='mailgun_base_url' name='mailgun_base_url' type='text'
						   {% if mailgun_base_url is defined and mailgun_base_url != None %}value="{{ mailgun_base_url }}"{% endif %}>
				</div>
				<div class="form-group">
					<label>
						Mailgun API Key<br>
						<small class="form-text text-muted">
							Mailgun API Key
						</small>
					</label>
					<input class="form-control" id='mailgun_api_key' name='mailgun_api_key' type='text'
						   {% if mailgun_api_key is defined and mailgun_api_key != None %}value="{{ mailgun_api_key }}"{% endif %}>
				</div>
			</div>
		</div>
		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/mlc.html
<div role="tabpanel" class="tab-pane config-section" id="mlc">
	<form method="POST" autocomplete="off" class="w-100">

		<div class="form-group">
			<label>
				Client ID
				<small class="form-text text-muted">
					OAuth Client ID for <a href="https://majorleaguecyber.org/">MajorLeagueCyber</a> integration.
				</small>
			</label>
			<input class="form-control" id='oauth_client_id' name='oauth_client_id' type='text'
				   placeholder=""
				   {% if oauth_client_id is defined and oauth_client_id != None %}value="{{ oauth_client_id }}"{% endif %}>
		</div>

		<div class="form-group">
			<label>
				Client Secret
				<small class="form-text text-muted">
					OAuth Client Secret for <a href="https://majorleaguecyber.org/">MajorLeagueCyber</a> integration.
				</small>
			</label>
			<input class="form-control" id='oauth_client_secret' name='oauth_client_secret' type='text'
				   placeholder=""
				   {% if oauth_client_secret is defined and oauth_client_secret != None %}value="{{ oauth_client_secret }}"{% endif %}>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/settings.html
<div role="tabpanel" class="tab-pane config-section" id="settings">
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<label>
				Challenge Visibility<br>
				<small class="form-text text-muted">
					Control whether users must be logged in to see challenges
				</small>
			</label>
			<select class="form-control custom-select" name="challenge_visibility">
				<option value="public" {% if challenge_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if challenge_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
				<option value="admins" {% if challenge_visibility == 'admins' %}selected{% endif %}>
					Admins Only
				</option>
			</select>
		</div>

		<div class="form-group">
			<label>
				Score Visibility<br>
				<small class="form-text text-muted">
					Control whether solves/score are shown to the public, to logged in users, hidden to all non-admins, or only shown to admins
				</small>
			</label>
			<select class="form-control custom-select" name="score_visibility">
				<option value="public" {% if score_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if score_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
				<option value="hidden" {% if score_visibility == 'hidden' %}selected{% endif %}>
					Hidden
				</option>
				<option value="admins" {% if score_visibility == 'admins' %}selected{% endif %}>
					Admins Only
				</option>
			</select>
			<small class="form-text text-muted">
				This setting should generally be the same as Account Visibility to avoid conflicts.
			</small>
		</div>

		<div class="form-group">
			<label>
				Account Visibility<br>
				<small class="form-text text-muted">
					Control whether accounts (users &amp; teams) are shown to everyone, only to authenticated users, or only to admins
				</small>
			</label>
			<select class="form-control custom-select" name="account_visibility">
				<option value="public" {% if account_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if account_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
				<option value="admins" {% if account_visibility == 'admins' %}selected{% endif %}>
					Admins Only
				</option>
			</select>
			<small class="form-text text-muted">
				This setting should generally be the same as Score Visibility to avoid conflicts.
			</small>
		</div>

		<div class="form-group">
			<label>
				Registration Visibility<br>
				<small class="form-text text-muted">
					Control whether registration is enabled for everyone or disabled
				</small>
			</label>
			<select class="form-control custom-select" name="registration_visibility">
				<option value="public" {% if registration_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if registration_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
				<option value="mlc" {% if registration_visibility == 'mlc' %}selected{% endif %}>
					MajorLeagueCyber Only
				</option>
			</select>
		</div>

		<div class="form-group">
			<div class="form-check">
				<label>
					<input id="paused" name="paused" type="checkbox" {% if paused %}checked{% endif %}>
					Pause CTF<br>
					<small>
						Prevent users from submitting answers until unpaused. Challenges can still be viewed.
					</small>
				</label>
			</div>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>